# -*- coding: utf-8 -*-
"""TechChallange1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YgYJ7OWwHbxoS3vj77lawEoS5Nuprs2f
"""

import pandas as pd

"""## 1 Extração dos dados

#1.1 Produção de 2007 até 2021
"""

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2007&opcao=opt_02')
producao2007 = leitura[5]
producao2007.head()

producao2007 = producao2007.rename(columns={"Quantidade (L.)" : "2007"})
producao2007.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2008&opcao=opt_02')
producao2008 = leitura[5]
producao2008.head()

producao2008 = producao2008.rename(columns={"Quantidade (L.)" : "2008"})
producao2008.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2009&opcao=opt_02')
producao2009 = leitura[5]
producao2009.head()

producao2009 = producao2009.rename(columns={"Quantidade (L.)" : "2009"})
producao2009.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2010&opcao=opt_02')
producao2010 = leitura[5]
producao2010.head()

producao2010 = producao2010.rename(columns={"Quantidade (L.)" : "2010"})
producao2010.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2011&opcao=opt_02')
producao2011 = leitura[5]
producao2011.head()

producao2011 = producao2011.rename(columns={"Quantidade (L.)" : "2011"})
producao2011.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2012&opcao=opt_02')
producao2012 = leitura[5]
producao2012.head()

producao2012 = producao2012.rename(columns={"Quantidade (L.)" : "2012"})
producao2012.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2013&opcao=opt_02')
producao2013 = leitura[5]
producao2013.head()

producao2013 = producao2013.rename(columns={"Quantidade (L.)" : "2013"})
producao2013.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2014&opcao=opt_02')
producao2014 = leitura[5]
producao2014.head()

producao2014 = producao2014.rename(columns={"Quantidade (L.)" : "2014"})
producao2014.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2015&opcao=opt_02')
producao2015 = leitura[5]
producao2015.head()

producao2015 = producao2015.rename(columns={"Quantidade (L.)" : "2015"})
producao2015.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2016&opcao=opt_02')
producao2016 = leitura[5]
producao2016.head()

producao2016 = producao2016.rename(columns={"Quantidade (L.)" : "2016"})
producao2016.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2017&opcao=opt_02')
producao2017 = leitura[5]
producao2017.head()

producao2017 = producao2017.rename(columns={"Quantidade (L.)" : "2017"})
producao2017.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2018&opcao=opt_02')
producao2018 = leitura[5]
producao2018.head()

producao2018 = producao2018.rename(columns={"Quantidade (L.)" : "2018"})
producao2018.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2019&opcao=opt_02')
producao2019 = leitura[5]
producao2019.head()

producao2019 = producao2019.rename(columns={"Quantidade (L.)" : "2019"})
producao2019.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2020&opcao=opt_02')
producao2020 = leitura[5]
producao2020.head()

producao2020 = producao2020.rename(columns={"Quantidade (L.)" : "2020"})
producao2020.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2021&opcao=opt_02')
producao2021 = leitura[5]
producao2021.head()

producao2021 = producao2021.rename(columns={"Quantidade (L.)" : "2021"})
producao2021.head()

producao_total = pd.concat([producao2007, producao2008, producao2009, producao2010, producao2011, producao2012, producao2013,
                            producao2014, producao2015, producao2016, producao2017, producao2018, producao2019, producao2020, producao2021], axis=1)
producao_total.head()

producao_total.to_excel('producao_total.xlsx', index=False)

"""# 1.2 exportação de Vinho de 2007 até 2021"""

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2007&opcao=opt_06&subopcao=subopt_01')
exportacao2007 = leitura[5]
exportacao2007.head()

exportacao2007 = exportacao2007.rename(columns={"Quantidade (Kg)" : "2007 (Ltr)", "Valor (US$)" : "2007 Valor (USD)"})
exportacao2007.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2008&opcao=opt_06&subopcao=subopt_01')
exportacao2008 = leitura[5]
exportacao2008.head()

exportacao2008 = exportacao2008.rename(columns={"Quantidade (Kg)" : "2008 (Ltr)", "Valor (US$)" : "2008 Valor (USD)"})
exportacao2008.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2009&opcao=opt_06&subopcao=subopt_01')
exportacao2009 = leitura[5]
exportacao2009.head()

exportacao2009 = exportacao2009.rename(columns={"Quantidade (Kg)" : "2009 (Ltr)", "Valor (US$)" : "2009 Valor (USD)"})
exportacao2009.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2010&opcao=opt_06&subopcao=subopt_01')
exportacao2010 = leitura[5]
exportacao2010.head()

exportacao2010 = exportacao2010.rename(columns={"Quantidade (Kg)" : "2010 (Ltr)", "Valor (US$)" : "2010 Valor (USD)"})
exportacao2010.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2011&opcao=opt_06&subopcao=subopt_01')
exportacao2011 = leitura[5]
exportacao2011.head()

exportacao2011 = exportacao2011.rename(columns={"Quantidade (Kg)" : "2011 (Ltr)", "Valor (US$)" : "2011 Valor (USD)"})
exportacao2011.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2012&opcao=opt_06&subopcao=subopt_01')
exportacao2012 = leitura[5]
exportacao2012.head()

exportacao2012 = exportacao2012.rename(columns={"Quantidade (Kg)" : "2012 (Ltr)", "Valor (US$)" : "2012 Valor (USD)"})
exportacao2012.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2013&opcao=opt_06&subopcao=subopt_01')
exportacao2013 = leitura[5]
exportacao2013.head()

exportacao2013 = exportacao2013.rename(columns={"Quantidade (Kg)" : "2013 (Ltr)", "Valor (US$)" : "2013 Valor (USD)"})
exportacao2013.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2014&opcao=opt_06&subopcao=subopt_01')
exportacao2014 = leitura[5]
exportacao2014.head()

exportacao2014 = exportacao2014.rename(columns={"Quantidade (Kg)" : "2014 (Ltr)", "Valor (US$)" : "2014 Valor (USD)"})
exportacao2014.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2015&opcao=opt_06&subopcao=subopt_01')
exportacao2015 = leitura[5]
exportacao2015.head()

exportacao2015 = exportacao2015.rename(columns={"Quantidade (Kg)" : "2015 (Ltr)", "Valor (US$)" : "2015 Valor (USD)"})
exportacao2015.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2016&opcao=opt_06&subopcao=subopt_01')
exportacao2016 = leitura[5]
exportacao2016.head()

exportacao2016 = exportacao2016.rename(columns={"Quantidade (Kg)" : "2016 (Ltr)", "Valor (US$)" : "2016 Valor (USD)"})
exportacao2016.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2017&opcao=opt_06&subopcao=subopt_01')
exportacao2017 = leitura[5]
exportacao2017.head()

exportacao2017 = exportacao2017.rename(columns={"Quantidade (Kg)" : "2017 (Ltr)", "Valor (US$)" : "2017 Valor (USD)"})
exportacao2017.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2018&opcao=opt_06&subopcao=subopt_01')
exportacao2018 = leitura[5]
exportacao2018.head()

exportacao2018 = exportacao2018.rename(columns={"Quantidade (Kg)" : "2018 (Ltr)", "Valor (US$)" : "2018 Valor (USD)"})
exportacao2018.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2019&opcao=opt_06&subopcao=subopt_01')
exportacao2019 = leitura[5]
exportacao2019.head()

exportacao2019 = exportacao2019.rename(columns={"Quantidade (Kg)" : "2019 (Ltr)", "Valor (US$)" : "2019 Valor (USD)"})
exportacao2019.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2020&opcao=opt_06&subopcao=subopt_01')
exportacao2020 = leitura[5]
exportacao2020.head()

exportacao2020 = exportacao2020.rename(columns={"Quantidade (Kg)" : "2020 (Ltr)", "Valor (US$)" : "2020 Valor (USD)"})
exportacao2020.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2021&opcao=opt_06&subopcao=subopt_01')
exportacao2021 = leitura[5]
exportacao2021.head()

exportacao2021 = exportacao2021.rename(columns={"Quantidade (Kg)" : "2021 (Ltr)", "Valor (US$)" : "2021 Valor (USD)"})
exportacao2021.head()

exportacao_total = pd.concat([exportacao2007, exportacao2008, exportacao2009, exportacao2010, exportacao2011, exportacao2012, exportacao2013,
                            exportacao2014, exportacao2015, exportacao2016, exportacao2017, exportacao2018, exportacao2019, exportacao2020, exportacao2021], axis=1)
exportacao_total.head()

exportacao_total.to_excel('exportacao_total.xlsx', index=False)

"""# 1.3 Exportação espumantes de 2007 até 2021"""

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2007&opcao=opt_06&subopcao=subopt_02')
exportacao_esp_2007 = leitura[5]
exportacao_esp_2007.head()

exportacao_esp_2007 = exportacao_esp_2007.rename(columns={"Quantidade (Kg)" : "2007 (Ltr)", "Valor (US$)" : "2007 Valor (USD)"})
exportacao_esp_2007.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2008&opcao=opt_06&subopcao=subopt_02')
exportacao_esp_2008 = leitura[5]
exportacao_esp_2008.head()

exportacao_esp_2008 = exportacao_esp_2008.rename(columns={"Quantidade (Kg)" : "2008 (Ltr)", "Valor (US$)" : "2008 Valor (USD)"})
exportacao_esp_2008.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2009&opcao=opt_06&subopcao=subopt_02')
exportacao_esp_2009 = leitura[5]
exportacao_esp_2009.head()

exportacao_esp_2009 = exportacao_esp_2009.rename(columns={"Quantidade (Kg)" : "2009 (Ltr)", "Valor (US$)" : "2009 Valor (USD)"})
exportacao_esp_2009.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2010&opcao=opt_06&subopcao=subopt_02')
exportacao_esp_2010 = leitura[5]
exportacao_esp_2010.head()

exportacao_esp_2010 = exportacao_esp_2010.rename(columns={"Quantidade (Kg)" : "2010 (Ltr)", "Valor (US$)" : "2010 Valor (USD)"})
exportacao_esp_2010.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2011&opcao=opt_06&subopcao=subopt_02')
exportacao_esp_2011 = leitura[5]
exportacao_esp_2011.head()

exportacao_esp_2011 = exportacao_esp_2011.rename(columns={"Quantidade (Kg)" : "2011 (Ltr)", "Valor (US$)" : "2011 Valor (USD)"})
exportacao_esp_2011.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2012&opcao=opt_06&subopcao=subopt_02')
exportacao_esp_2012 = leitura[5]
exportacao_esp_2012.head()

exportacao_esp_2012 = exportacao_esp_2012.rename(columns={"Quantidade (Kg)" : "2012 (Ltr)", "Valor (US$)" : "2012 Valor (USD)"})
exportacao_esp_2012.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2013&opcao=opt_06&subopcao=subopt_02')
exportacao_esp_2013 = leitura[5]
exportacao_esp_2013.head()

exportacao_esp_2013 = exportacao_esp_2013.rename(columns={"Quantidade (Kg)" : "2013 (Ltr)", "Valor (US$)" : "2013 Valor (USD)"})
exportacao_esp_2013.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2014&opcao=opt_06&subopcao=subopt_02')
exportacao_esp_2014 = leitura[5]
exportacao_esp_2014.head()

exportacao_esp_2014 = exportacao_esp_2014.rename(columns={"Quantidade (Kg)" : "2014 (Ltr)", "Valor (US$)" : "2014 Valor (USD)"})
exportacao_esp_2014.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2015&opcao=opt_06&subopcao=subopt_02')
exportacao_esp_2015 = leitura[5]
exportacao_esp_2015.head()

exportacao_esp_2015 = exportacao_esp_2015.rename(columns={"Quantidade (Kg)" : "2015 (Ltr)", "Valor (US$)" : "2015 Valor (USD)"})
exportacao_esp_2015.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2016&opcao=opt_06&subopcao=subopt_02')
exportacao_esp_2016 = leitura[5]
exportacao_esp_2016.head()

exportacao_esp_2016 = exportacao_esp_2016.rename(columns={"Quantidade (Kg)" : "2016 (Ltr)", "Valor (US$)" : "2016 Valor (USD)"})
exportacao_esp_2016.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2017&opcao=opt_06&subopcao=subopt_02')
exportacao_esp_2017 = leitura[5]
exportacao_esp_2017.head()

exportacao_esp_2017 = exportacao_esp_2017.rename(columns={"Quantidade (Kg)" : "2017 (Ltr)", "Valor (US$)" : "2017 Valor (USD)"})
exportacao_esp_2017.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2018&opcao=opt_06&subopcao=subopt_02')
exportacao_esp_2018 = leitura[5]
exportacao_esp_2018.head()

exportacao_esp_2018 = exportacao_esp_2018.rename(columns={"Quantidade (Kg)" : "2018 (Ltr)", "Valor (US$)" : "2018 Valor (USD)"})
exportacao_esp_2018.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2019&opcao=opt_06&subopcao=subopt_02')
exportacao_esp_2019 = leitura[5]
exportacao_esp_2019.head()

exportacao_esp_2019 = exportacao_esp_2019.rename(columns={"Quantidade (Kg)" : "2019 (Ltr)", "Valor (US$)" : "2019 Valor (USD)"})
exportacao_esp_2019.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2020&opcao=opt_06&subopcao=subopt_02')
exportacao_esp_2020 = leitura[5]
exportacao_esp_2020.head()

exportacao_esp_2020 = exportacao_esp_2020.rename(columns={"Quantidade (Kg)" : "2020 (Ltr)", "Valor (US$)" : "2020 Valor (USD)"})
exportacao_esp_2020.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2021&opcao=opt_06&subopcao=subopt_02')
exportacao_esp_2021 = leitura[5]
exportacao_esp_2021.head()

exportacao_esp_2021 = exportacao_esp_2021.rename(columns={"Quantidade (Kg)" : "2021 (Ltr)", "Valor (US$)" : "2021 Valor (USD)"})
exportacao_esp_2021.head()

exportacao_esp_total = pd.concat([exportacao_esp_2007, exportacao_esp_2008, exportacao_esp_2009, exportacao_esp_2010, exportacao_esp_2011, exportacao_esp_2012, exportacao_esp_2013,
                            exportacao_esp_2014, exportacao_esp_2015, exportacao_esp_2016, exportacao_esp_2017, exportacao_esp_2018, exportacao_esp_2019, exportacao_esp_2020, exportacao_esp_2021], axis=1)
exportacao_esp_total.head()

exportacao_esp_total.to_excel('exportacao_esp_total.xlsx', index=False)

"""# 1.4 Processamento de Uvas Tipo Viníferas de 2007 até 2021"""

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2007&opcao=opt_03&subopcao=subopt_01')
proces_vinifera_2007 = leitura[5]
proces_vinifera_2007.head()

proces_vinifera_2007 = proces_vinifera_2007.rename(columns={"Quantidade (Kg)" : "2007 (Ltr)"})
proces_vinifera_2007.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2008&opcao=opt_03&subopcao=subopt_01')
proces_vinifera_2008 = leitura[5]
proces_vinifera_2008.head()

proces_vinifera_2008 = proces_vinifera_2008.rename(columns={"Quantidade (Kg)" : "2008 (Ltr)"})
proces_vinifera_2008.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2009&opcao=opt_03&subopcao=subopt_01')
proces_vinifera_2009 = leitura[5]
proces_vinifera_2009.head()

proces_vinifera_2009 = proces_vinifera_2009.rename(columns={"Quantidade (Kg)" : "2009 (Ltr)"})
proces_vinifera_2009.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2010&opcao=opt_03&subopcao=subopt_01')
proces_vinifera_2010 = leitura[5]
proces_vinifera_2010.head()

proces_vinifera_2010 = proces_vinifera_2010.rename(columns={"Quantidade (Kg)" : "2010 (Ltr)"})
proces_vinifera_2010.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2011&opcao=opt_03&subopcao=subopt_01')
proces_vinifera_2011 = leitura[5]
proces_vinifera_2011.head()

proces_vinifera_2011 = proces_vinifera_2011.rename(columns={"Quantidade (Kg)" : "2011 (Ltr)"})
proces_vinifera_2011.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2012&opcao=opt_03&subopcao=subopt_01')
proces_vinifera_2012 = leitura[5]
proces_vinifera_2012.head()

proces_vinifera_2012 = proces_vinifera_2012.rename(columns={"Quantidade (Kg)" : "2012 (Ltr)"})
proces_vinifera_2012.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2013&opcao=opt_03&subopcao=subopt_01')
proces_vinifera_2013 = leitura[5]
proces_vinifera_2013.head()

proces_vinifera_2013 = proces_vinifera_2013.rename(columns={"Quantidade (Kg)" : "2013 (Ltr)"})
proces_vinifera_2013.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2014&opcao=opt_03&subopcao=subopt_01')
proces_vinifera_2014 = leitura[5]
proces_vinifera_2014.head()

proces_vinifera_2014 = proces_vinifera_2014.rename(columns={"Quantidade (Kg)" : "2014 (Ltr)"})
proces_vinifera_2014.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2015&opcao=opt_03&subopcao=subopt_01')
proces_vinifera_2015 = leitura[5]
proces_vinifera_2015.head()

proces_vinifera_2015 = proces_vinifera_2015.rename(columns={"Quantidade (Kg)" : "2015 (Ltr)"})
proces_vinifera_2015.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2016&opcao=opt_03&subopcao=subopt_01')
proces_vinifera_2016 = leitura[5]
proces_vinifera_2016.head()

proces_vinifera_2016 = proces_vinifera_2016.rename(columns={"Quantidade (Kg)" : "2016 (Ltr)"})
proces_vinifera_2016.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2017&opcao=opt_03&subopcao=subopt_01')
proces_vinifera_2017 = leitura[5]
proces_vinifera_2017.head()

proces_vinifera_2017 = proces_vinifera_2017.rename(columns={"Quantidade (Kg)" : "2017 (Ltr)"})
proces_vinifera_2017.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2018&opcao=opt_03&subopcao=subopt_01')
proces_vinifera_2018 = leitura[5]
proces_vinifera_2018.head()

proces_vinifera_2018 = proces_vinifera_2018.rename(columns={"Quantidade (Kg)" : "2018 (Ltr)"})
proces_vinifera_2018.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2019&opcao=opt_03&subopcao=subopt_01')
proces_vinifera_2019 = leitura[5]
proces_vinifera_2019.head()

proces_vinifera_2019 = proces_vinifera_2019.rename(columns={"Quantidade (Kg)" : "2019 (Ltr)"})
proces_vinifera_2019.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2020&opcao=opt_03&subopcao=subopt_01')
proces_vinifera_2020 = leitura[5]
proces_vinifera_2020.head()

proces_vinifera_2020 = proces_vinifera_2020.rename(columns={"Quantidade (Kg)" : "2020 (Ltr)"})
proces_vinifera_2020.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2021&opcao=opt_03&subopcao=subopt_01')
proces_vinifera_2021 = leitura[5]
proces_vinifera_2021.head()

proces_vinifera_2021 = proces_vinifera_2021.rename(columns={"Quantidade (Kg)" : "2021 (Ltr)"})
proces_vinifera_2021.head()

proces_vinifera_total = pd.concat([proces_vinifera_2007, proces_vinifera_2008, proces_vinifera_2009, proces_vinifera_2010, proces_vinifera_2011, proces_vinifera_2012, proces_vinifera_2013,
                            proces_vinifera_2014, proces_vinifera_2015, proces_vinifera_2016, proces_vinifera_2017, proces_vinifera_2018, proces_vinifera_2019, proces_vinifera_2020, proces_vinifera_2021], axis=1)
proces_vinifera_total.head()

proces_vinifera_total.to_excel('proces_vinifera_total.xlsx', index=False)

"""# 1.5 Processamento de Uvas tipo Americana e Hibridas de 2007 até 2021"""

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2007&opcao=opt_03&subopcao=subopt_02')
proces_ame_e_hib_2007 = leitura[5]
proces_ame_e_hib_2007.head()

proces_ame_e_hib_2007 = proces_ame_e_hib_2007.rename(columns={"Quantidade (Kg)" : "2007 (Ltr)"})
proces_ame_e_hib_2007.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2008&opcao=opt_03&subopcao=subopt_02')
proces_ame_e_hib_2008 = leitura[5]
proces_ame_e_hib_2008.head()

proces_ame_e_hib_2008 = proces_ame_e_hib_2008.rename(columns={"Quantidade (Kg)" : "2008 (Ltr)"})
proces_ame_e_hib_2008.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2009&opcao=opt_03&subopcao=subopt_02')
proces_ame_e_hib_2009 = leitura[5]
proces_ame_e_hib_2009.head()

proces_ame_e_hib_2009 = proces_ame_e_hib_2009.rename(columns={"Quantidade (Kg)" : "2009 (Ltr)"})
proces_ame_e_hib_2009.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2010&opcao=opt_03&subopcao=subopt_02')
proces_ame_e_hib_2010 = leitura[5]
proces_ame_e_hib_2010.head()

proces_ame_e_hib_2010 = proces_ame_e_hib_2010.rename(columns={"Quantidade (Kg)" : "2010 (Ltr)"})
proces_ame_e_hib_2010.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2011&opcao=opt_03&subopcao=subopt_02')
proces_ame_e_hib_2011 = leitura[5]
proces_ame_e_hib_2011.head()

proces_ame_e_hib_2011 = proces_ame_e_hib_2011.rename(columns={"Quantidade (Kg)" : "2011 (Ltr)"})
proces_ame_e_hib_2011.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2012&opcao=opt_03&subopcao=subopt_02')
proces_ame_e_hib_2012 = leitura[5]
proces_ame_e_hib_2012.head()

proces_ame_e_hib_2012 = proces_ame_e_hib_2012.rename(columns={"Quantidade (Kg)" : "2012 (Ltr)"})
proces_ame_e_hib_2012.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2013&opcao=opt_03&subopcao=subopt_02')
proces_ame_e_hib_2013 = leitura[5]
proces_ame_e_hib_2013.head()

proces_ame_e_hib_2013 = proces_ame_e_hib_2013.rename(columns={"Quantidade (Kg)" : "2013 (Ltr)"})
proces_ame_e_hib_2013.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2014&opcao=opt_03&subopcao=subopt_02')
proces_ame_e_hib_2014 = leitura[5]
proces_ame_e_hib_2014.head()

proces_ame_e_hib_2014 = proces_ame_e_hib_2014.rename(columns={"Quantidade (Kg)" : "2014 (Ltr)"})
proces_ame_e_hib_2014.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2015&opcao=opt_03&subopcao=subopt_02')
proces_ame_e_hib_2015 = leitura[5]
proces_ame_e_hib_2015.head()

proces_ame_e_hib_2015 = proces_ame_e_hib_2015.rename(columns={"Quantidade (Kg)" : "2015 (Ltr)"})
proces_ame_e_hib_2015.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2016&opcao=opt_03&subopcao=subopt_02')
proces_ame_e_hib_2016 = leitura[5]
proces_ame_e_hib_2016.head()

proces_ame_e_hib_2016 = proces_ame_e_hib_2016.rename(columns={"Quantidade (Kg)" : "2016 (Ltr)"})
proces_ame_e_hib_2016.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2017&opcao=opt_03&subopcao=subopt_02')
proces_ame_e_hib_2017 = leitura[5]
proces_ame_e_hib_2017.head()

proces_ame_e_hib_2017 = proces_ame_e_hib_2017.rename(columns={"Quantidade (Kg)" : "2017 (Ltr)"})
proces_ame_e_hib_2017.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2018&opcao=opt_03&subopcao=subopt_02')
proces_ame_e_hib_2018 = leitura[5]
proces_ame_e_hib_2018.head()

proces_ame_e_hib_2018 = proces_ame_e_hib_2018.rename(columns={"Quantidade (Kg)" : "2018 (Ltr)"})
proces_ame_e_hib_2018.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2019&opcao=opt_03&subopcao=subopt_02')
proces_ame_e_hib_2019 = leitura[5]
proces_ame_e_hib_2019.head()

proces_ame_e_hib_2019 = proces_ame_e_hib_2019.rename(columns={"Quantidade (Kg)" : "2019 (Ltr)"})
proces_ame_e_hib_2019.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2020&opcao=opt_03&subopcao=subopt_02')
proces_ame_e_hib_2020 = leitura[5]
proces_ame_e_hib_2020.head()

proces_ame_e_hib_2020 = proces_ame_e_hib_2020.rename(columns={"Quantidade (Kg)" : "2020 (Ltr)"})
proces_ame_e_hib_2020.head()

leitura = pd.read_html('http://vitibrasil.cnpuv.embrapa.br/index.php?ano=2021&opcao=opt_03&subopcao=subopt_02')
proces_ame_e_hib_2021 = leitura[5]
proces_ame_e_hib_2021.head()

proces_ame_e_hib_2021 = proces_ame_e_hib_2021.rename(columns={"Quantidade (Kg)" : "2021 (Ltr)"})
proces_ame_e_hib_2021.head()

proces_ame_e_hib_total = pd.concat([proces_ame_e_hib_2007, proces_ame_e_hib_2008, proces_ame_e_hib_2009, proces_ame_e_hib_2010, proces_ame_e_hib_2011, proces_ame_e_hib_2012, proces_ame_e_hib_2013,
                            proces_ame_e_hib_2014, proces_ame_e_hib_2015, proces_ame_e_hib_2016, proces_ame_e_hib_2017, proces_ame_e_hib_2018, proces_ame_e_hib_2019, proces_ame_e_hib_2020, proces_ame_e_hib_2021], axis=1)
proces_ame_e_hib_total.head()

proces_ame_e_hib_total.to_excel('proces_ame_e_hib_total.xlsx', index=False)

"""#1.6 Criação de coluna com preço médio por Litro"""

exportacao_total_vinho = pd.read_excel("/content/exportacao_total.xlsx")
exportacao_total_vinho.head()

exportacao_total_vinho = exportacao_total_vinho.replace("-", 0)
exportacao_total_vinho.head()

import numpy as np

def safe_division(x, y):
    if y != 0:
        return x / y
    else:
        return 0

for year in range(2007, 2021):
    valor1_col = f"{year} (Ltr)"
    valor2_col = f"{year} Valor (USD)"
    media_ = f'media_{year}'
    exportacao_total_vinho.loc[:, valor1_col] = pd.to_numeric(exportacao_total_vinho[valor1_col], errors='coerce')
    exportacao_total_vinho.loc[:, valor2_col] = pd.to_numeric(exportacao_total_vinho[valor2_col], errors='coerce')
    exportacao_total_vinho.loc[:, media_] = exportacao_total_vinho.apply(lambda row: safe_division(row[valor2_col], row[valor1_col]), axis=1)

# Reorganizando as colunas na ordem desejada
columns_ordered = []
for year in range(2007, 2021):
    valor1_col = f"{year} (Ltr)"
    valor2_col = f"{year} Valor (USD)"
    media_ = f'media_{year}'
    columns_ordered.extend([valor1_col, valor2_col, media_])

exportacao_total_vinho = exportacao_total_vinho[columns_ordered]
exportacao_total_vinho.fillna(0, inplace=True)

exportacao_total_vinho.head()